version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - FLASK_ENVIORMENT=local
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
  